# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_major', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='live.Cluster')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='live.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='cluster',
            field=models.ManyToManyField(through='live.Scores', to='live.Cluster'),
        ),
    ]
