# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(help_text='The name of this cluster.', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='The name of this event.', max_length=30, primary_key=True, serialize=False),
        ),
    ]
